version: 2
updates:
  # Maintain dependencies for Cargo (Rust)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      bevy:
        patterns:
          - "bevy*"
      rust-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "bevy*"
    open-pull-requests-limit: 15
    commit-message:
      prefix: "cargo"
      include: "scope"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 15
    commit-message:
      prefix: "github-actions"
      include: "scope"
