[package]
name = "my-rts-game"
version = "0.1.0"
edition = "2021"

[profile.ci]
inherits = "release"
debug = false
opt-level = 2
codegen-units = 16
lto = "thin"

[dependencies]
bevy = "0.14.2"
winit = "0.30"

[build-dependencies]
winres = "0.1"
